# hidden for now 

language: node_js
deploy:
  provider: codedeploy
  access_key_id: AKIAIRHP2XLBEUHPJEHQ
  secret_access_key:
    secure: KSP1JDjwuyvzNTgrtsa+3m0KLOmHo6Bwlu7HF5DE998s5c0Sn9dK0OsyYzGFGS3abyOjbUr/oit7sMbcuxkbg+LLUNmtoUbnxvT1KxL6Y4QlGrT2pIad+tr3BxiNtVbe8zu6ooJRMK0uYzjePjfx24FPmLSYD83AlNzBTjxboo954JPxQPx/HVAB6ZDmhQ4ylZCq33AtaCbiMW0BOkOgg56PkOUmarxAbChbwBZzGQAvchzA/tH+yRg/GI+ep0MrjUX2zOIl1oftRO7KkAVZL2aSv4md30zTadcbLkyezgL6+0KpTtQoygM19ET2qsx+XI/laLi/UfEGPtALs8TqAt17M3L0ueuA+LIzdVTmnKmIyqEmTJ+Kiazz08BjnAHmwrcwbGo6NmC+TD2rWKuvqT6ffBTATd3iPC/TjfujveURKWzvJzmBD+ScZexXMBWQlnr1gHCIzHI3KZ+NJmNHA4lib5SmNwv8JF1r2ecwtzcf4Q5/N0am8tjvTKgeP47Av2W3575euE14Zx4s4VX1VNv2C5EVj/t41BwsI1XyFyo5/HGezmPJ6hPN4daU7q2W2S0WXvt+5i5tB5YZIVRkZ76Dv5/H/5o5htffHNZ9yAvVHw3aRBj123EOzy7Dh3fVlCebZl83sQGFHClSKpLIEVDuTEYYhZheoJenE+Hljjw=
  application: Swoon
  deployment_group: SwoonCodeDeploy
  on:
    repo: DanielKRing1/SwoonBot
  region: us-west-1

after_deploy: "./travis/after_deploy_1.sh"
